Codeinwp/feedzy-rss-feeds

- css/feedzy-rss-feeds.css
- feedzy-rss-feed.php
- includes/abstract/feedzy-rss-feeds-admin-abstract.php
- includes/feedzy-rss-feeds.php
- package.json
- readme.txt
Removed alt tags from span elements and replaced them with title tags. Fixes https://github.com/Codeinwp/feedzy-rss-feeds/issues/46
Also, added myself as a contributor for support purposes.
> Replace alt in span with title

- includes/abstract/feedzy-rss-feeds-admin-abstract.php
Removed double protocol from the author URL and replaced it with //.  Fixes: https://github.com/Codeinwp/feedzy-rss-feeds/issues/48
> Fix author URL protocol

- includes/abstract/feedzy-rss-feeds-admin-abstract.php
Bug: #41304 with WP wp_kses sanitizer
Added a temporary method to avoid using WP default implementation.
Fixes feed images URL's in some cases.
Open issue: https://core.trac.wordpress.org/ticket/41304
> FIX: (Made changes to SimplePie instantiation)

- includes/abstract/feedzy-rss-feeds-admin-abstract.php
https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/305
> Image with encoded URL does not get imported

- includes/views/import-metabox-edit.php
> Changed help text in post taxonomy field

- includes/admin/feedzy-rss-feeds-admin.php
- phpunit.xml
- tests/test-post-access.php
Changed capabilities for accesing custom post type to match with the menu availability.
Added unit test for this.
1. Create multiple accounts with different roles. ( Administrator, Contributor, Editor)
2. Check that only the Administrator can access the custom feedzy categories
Closes: Codeinwp/feedzy-rss-feeds-pro#674
> fix: capabilities for feedzy categories

- includes/admin/feedzy-rss-feeds-admin.php
- includes/feedzy-rss-feeds.php
Reworked the capabilities and registered the capabilities for the administrator role.
1. Create a new category
2. Check that all actions are usable, edit, delete, create, and assign to import.
3. Check that Import works as before.
Closes:  Codeinwp/feedzy-rss-feeds-pro#676
> fix: add capabilities to administrator and change structure

- includes/admin/feedzy-rss-feeds-admin.php
- js/survey.js
- Add code to initiate NPS survey with Formbricks. 
- Collect attribute data
- Hook to settings pages except the About Us page.
Similar implementation also in:
- https://github.com/Codeinwp/multi-pages-plugin/pull/330
- https://github.com/Codeinwp/hestia-pro/pull/2617
- Check if your NPS survey shows up. (On a new session, it shows after 5 seconds)
> [!NOTE]
> If you want to re-trigger the survey, you will need to follow the same steps as here: https://github.com/Codeinwp/neve/pull/4186#issuecomment-1906364169
> Add NPS survey

- includes/admin/feedzy-rss-feeds-import.php
- Fixed a condition for a Pro feature that crashed the cron for free users. The bug was introduced in https://github.com/Codeinwp/feedzy-rss-feeds/commit/1a73ce68222d8efadfd9a97813e68949e61f7c72 for this issue https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/504
- Added a `try...catch` mechanism to stop possible errors from propagating inside the loop of the cron event.
> [!NOTE]
> This bug affected Free users; do not **install** the Pro version.
- Use links from this comment: https://github.com/Codeinwp/feedzy-rss-feeds/issues/883#issuecomment-1974173592
- Enable the debug and debug logs.
- Install the plugin that can run the cron job, like https://wordpress.org/plugins/advanced-cron-manager/
- Run the cron named `feedzy_job`.
- Check the logs if you see some errors with the …
> fix: prevent jobs from stopping the cron loop

- css/metabox-settings.css
- css/settings.css
- includes/layouts/feedzy-improve.php
- includes/views/import-metabox-edit.php
Closes #901 
- Appended to `.right` and `.left` the product suffix `fz-` to avoid conflict with other plugins CSS over generic names.
- Enforced the `text-align: left`.
1. Install Genesis Block plugin: https://wordpress.org/plugins/genesis-blocks/
2. Create a new feed
3. The layout should be like before.
> fix: css name conflict for `.right` class name

- css/settings.css
- includes/admin/feedzy-rss-feeds-import.php
- includes/views/js/import-metabox-edit.js
Allow mix content in the Title field on Map Content.
Changes:
- reducing the margin for the tags to allow better alignment with simple content
- made a special case for the title field tagify initialization
- before the mix content, the tags are saved as a list and transformed from `[[{"value":"[#item_title]"}], [{"value":"[#item_date]"}]]` to `[#item_title], [#item_date]`. With mix content enabled, the data is saved like this: `Title "[[{"value":"[#item_title]"}]]" on [[{"value":"[#item_date]"}]]`; a clean is done with regex to get `Title "[#item_title]" on [#item_date]`
NO
https://github.com/Codeinwp/feedzy-rss-feeds/assets/17597852/5745da03-6201-442b-a21b-a315a05872bd
- Create a new import
- In the Title Post field on Map Content, try to add a combination of text and tags ( do no use …
> fix: allow mix content in title field for map content

- feedzy-rss-feed.php
- includes/abstract/feedzy-rss-feeds-admin-abstract.php
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/899
When `full_content` magic tag is present, the endpoint will create a single feed with all the data. The feed is enhanced with custom tags under `feedzy` tag namespace.
With the changes from https://github.com/Codeinwp/feedzy-full-post/pull/89. The item feed looks like this:
```xml
<entry>
<guid>https://community.511tactical.com/5-11-announces-the-return-of-abr-academy-classes-for-2023-in-collaboration-with-uscca-copy/</guid>
<link href="https://www.511tactical.com/community/5-11-announces-the-return-of-abr-academy-classes-for-2023-in-collaboration-with-uscca-2/"/>
<title><![CDATA[5.11 Tactical to Celebrate 20th Anniversary]]></title>
<summary type="html"><![CDATA[
Celebrating its 20th anniversary, 5.11 Tactical reflects on its …
```
> feat: add tag parsing for feed source generated by endpoint

- composer.json
- composer.lock
Update the SDK
Closes https://github.com/Codeinwp/neve-pro-addon/issues/2785
> chore: sdk update

- cypress/e2e/gutenberg/gutenberg_free.js
- includes/admin/feedzy-rss-feeds-import.php
- tests/test-image-import.php
Fixed import for images from feeds where the image might contain encoded white space in the URL.
Added unit test to check for this case.
NO
<details open>
<summary>Mapping example for import</summary>
</details>
1. Use this feed to test with: https://fetchrss.com/rss/64e0dbc093190f2b1a5d40b264e22cf23a76e05a277d6673.xml
2. Ensure `[#item_image]` is used inside the content and featured image from mapping. See the Screenshot example.
3. Check that all images are imported.
Closes #917.
> fix: image import for images with spaces in url

- includes/abstract/feedzy-rss-feeds-admin-abstract.php
- tests/test-post-access.php
Extended the user admin check when displaying errors on the plugin setup interface.
I also added a test for this particular issue.
NO
Follow the issue details.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/709.
> fix: detailed errors for non admin access on admin screens

- cypress/e2e/gutenberg/gutenberg_free.js
- includes/abstract/feedzy-rss-feeds-admin-abstract.php
- includes/gutenberg/src/Editor.js
Added a checker that detects if the Feedzy default image is used when the thumbnail option is set to `auto` in the RSS block.
YES
- Create a simple import with the URL: https://themeisle.com/blog/feed/
- The default feedzy image should be shown unless it is set to show.
Closes #920
> Better checking for default image for the RSS Block

- includes/admin/feedzy-rss-feeds-import.php
- tests/test-import.php
Fix item date import to respect timezone settings.
Added unit test to validate item import date based on the timezone settings.
NO
<details open>
<summary>UTC</summary>
</details>
<details open>
<summary>UTC +2</summary>
</details>
1. On a fresh instance with Feedzy.
2. Set the `Timezone` from **Settings** > **General** to a desired locale.
3. Create a new import where we map the #item_date.
4. Import a feed, and check that the imported items are offset correctly on import based on <pubDate>
Closes #832.
> fix: change item_date to convert to site timezone on import

- includes/admin/feedzy-rss-feeds-import.php
- includes/views/js/import-metabox-edit.js
The feed setting dashboard did not have a memory to remember if the user did not want a fallback image. Thus, if you have the global fallback set, the dashboard will always use it.
After removing the fallback image from the feed settings and returning later for a short edit, if you do not re-check the fallback image settings and save, the global fallback image will be used; thus, the imported feeds will have the reported problem.
To solve this, I used the value `0` as a marking for `no fallback image`. When the user presses the `Remove` button in feed settings, `0` will be used as the image ID. The code already considered `0` as no fallback image, but it was never enabled for the user to use it.
NO
https://github.com/Codeinwp/feedzy-rss-feeds/assets/17597852/dcba8f50-880b-4f66-ab0f-e0fd188 …
> fix: allow user to exclude global fallback image in feed settings

- cypress/e2e/default/import_feed_free.js
- includes/admin/feedzy-rss-feeds-import.php
Allow the user to use its defined custom image tag.
NO
- Use this URL:  https://photojournal.jpl.nasa.gov/rss/targetFamily/Earth
- In the featured image use this: `[#item_custom_hiresJpeg]`
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/942
> fix: use the user defined custom image tag

- .github/workflows/create-tag.yml
Update the Node version for 18 for `create-tag` workflow.
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/931
> chore: update create-tag node version

- includes/admin/feedzy-rss-feeds-import.php
Add new fillter for item_url
I've added a new filter to add/remove item link attributes and change the link text.
Ref: https://tinyurl.com/22kqe3dm
Add the following code snippet to the functions.php file of your current active theme or in any custom plugin file:
```
add_filter(
'feedzy_item_link',
function ( $item_link_data, $item, $job ) {
// Change link text.
$item_link_data['text'] = 'LINK TEXT HERE';
// Add tracking parameters/UTMs.
$item_link_data['attr']['href'] = add_query_arg(
array(
'utm_source'   => '',
'utm_medium'   => '',
'utm_campaign' => '',
),
$item_link_data['attr']['href']
);
// Change link opening behavior.
$item_link_data['attr']['target'] = '_self'; // _blank, _self, _parent, _top
// Add link type - follow/nofollow link.
$item_link_data['attr']['rel'] = 'nofollow'; …
```
> Added new fillter for item_url

- includes/abstract/feedzy-rss-feeds-admin-abstract.php
In this PR I've excluded the feedzy default thumbnail used when the user clicks on the `preview import` button.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/700
> Fixed the issue with preview import data

- includes/admin/feedzy-rss-feeds-import.php
In this PR, I've removed the disabled legacy magic tags from the dropdown, also ensuring it does not impact existing users.
Closes #975
> Removed legacy magic tags from the dropdown

- css/settings.css
- includes/admin/feedzy-rss-feeds-actions.php
- js/ActionPopup/SortableItem.js
- js/ActionPopup/action-popup.js
In this PR, I've added modify links action to modify the `<a></a>` HTML attributes.
With Pro Version:
https://tinyurl.com/2ypn2944
https://tinyurl.com/23qrd67z
Without Pro version:
https://tinyurl.com/27xpoqg2
https://tinyurl.com/2b3gelle
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/647
> Add modify links action

- includes/admin/feedzy-rss-feeds-admin.php
I’ve removed `feedback.js` from other tabs and pages.
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/989
> Fixed javascript exception error

- .github/workflows/test-php.yml
- includes/admin/feedzy-rss-feeds-admin.php
- includes/admin/feedzy-rss-feeds-import.php
- includes/layouts/settings.php
- includes/layouts/setup-wizard.php
- includes/views/import-metabox-edit.php
- js/FeedzyBlock/Editor.js
- js/Onboarding/import-onboarding.js
- tests/e2e/specs/import.spec.js
- Rename Feed Categories to Feed Groups
- Add a filter to run_cron arguments
- Update feed and docs URL
YES/NO
- Make sure Feed Category has been renamed to Feed Group everywhere.
- https://github.com/Codeinwp/feedzy-rss-feeds/issues/937
- https://github.com/Codeinwp/feedzy-rss-feeds/issues/1003
- https://github.com/Codeinwp/feedzy-rss-feeds/issues/1012
- https://github.com/Codeinwp/feedzy-rss-feeds/issues/981
Also part of https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/793
> Various Improvements

- includes/abstract/feedzy-rss-feeds-admin-abstract.php
- includes/admin/feedzy-wp-widget.php
- includes/feedzy-rss-feeds.php
Fixed sidgets settings conflict with Lazy Loading in Elementor widget.
Yes
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/755
> Fixed cache data issue elementor widgets

- includes/admin/feedzy-rss-feeds-import.php
Added improvements to prevent resetting the Feedzy job data when the user clicks the `Cancel` button.
Yes
Here's how it behaves when the user clicks the `Cancel` button.
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/873
> Improved purge and reset button

- includes/admin/feedzy-rss-feeds-import.php
- includes/views/import-metabox-edit.php
Use visual tags instead of plain text as the default for Post Title & Content fields.
YES
- Make sure the importing works as before after the change.
Closes #1002.
> feat: use content tags in import fields

- includes/admin/feedzy-rss-feeds-import.php
After adding an import job to the queue, if the job was run through the cron, the post's author wasn't assigned. We make sure to always assign an author, as WordPress expects a post to have an author.
NO
- After an import job is run through job ( You can use WP Control to simulate that) it must always have the author assigned.
Closes #1013.
> fix: make sure post author is assigned to imported posts

- includes/admin/feedzy-rss-feeds-import.php
- includes/util/feedzy-rss-feeds-util-scheduler.php
This PR creates wrapper functions for WP_Cron in order to use Action Scheduler when available.
**Note:** This PR is made against https://github.com/Codeinwp/feedzy-rss-feeds/pull/1028 to cover latest cron uses added by the PR, and must be merged against the PR or to development after the initial PR is merged.
No
- Cron should work as before.
- To test with Action Scheduler, you can install WooCommerce and then use the plugin.
Closes #https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/785.
> feat: use action scheduler when available

- includes/abstract/feedzy-rss-feeds-admin-abstract.php
- includes/admin/feedzy-rss-feeds-import.php
- includes/feedzy-rss-feeds.php
- includes/views/import-metabox-edit.php
- phpcs.xml
- tests/e2e/specs/upsell.spec.js
Adds new cron schedule settings for per import job.
Yes
- Create an import job and configure a custom cron schedule.
- Wait for the default job to trigger, or install the WP-Control plugin to manually trigger the cron.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/572
> Added cron schedule settings per import job

- css/settings.css
- includes/admin/feedzy-rss-feeds-import.php
- includes/views/import-metabox-edit.php
- includes/views/js/import-metabox-edit.js
This adds a select field to choose the author for the imported posts in Feed import. If the author is not available in the list, as we only load 100 users, a custom username can also be typed there.
Yes
- We need to confirm the selected user is used as the author of imported posts.
- We should also make sure it works properly when upgrading from previous version.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/720.
> feat: add post author selection to Feed Imports

- includes/feedzy-rss-feeds-feed-tweaks.php
This PR uses the `wp_get_attachment_image_src` filter to make `wp_get_attachment_image_url` return the external URL for featured image.
Unrelated, I also prefixed an existing function with `feedzy_` to avoid possible conflicts.
YES/NO
- It should improve featured image handling with various third-party post grid/layout plugins that use `wp_get_attachment_image_url`
- For example, you can use Essential Addons for Elementor and their Timeline Block's Card Layout.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/738.
> feat: improve external featured image handling

- css/feedzy-rss-feed-import.css
- feedzy-rss-feed.php
- includes/admin/feedzy-rss-feeds-import.php
- includes/views/css/import-metabox-edit.css
- includes/views/js/import-metabox-edit.js
Adds error log storing features.
Yes
Option 1:
Activate a lower license plan and use higher plan magic tags in the import job.
Option 2:
Add the following code snippet to allow other error types:
```
add_filter(
'feedzy_allowed_store_log_types',
function ( $types ) {
$types[] = 'debug'; // info, warn
return $types;
}
);
```
Users can disable the error storing feature by adding the following code snippet:
```
add_filter( 'feedzy_skip_store_error_logs', '__return_true' );
```
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/701
> Store error logs for each import job

- css/settings.css
- includes/layouts/settings.php
- js/feedzy-setting.js
I've moved the license key section into feedzy general settings page.
Yes
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/805
> Move license key section

- css/settings.css
- includes/admin/feedzy-rss-feeds-admin.php
- includes/admin/feedzy-rss-feeds-import.php
- includes/layouts/settings.php
- includes/views/import-metabox-edit.php
- js/feedzy-setting.js
Information here: https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/802
Closes #https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/768.
> feat: Assign imported posts to categories based on the keywords

- css/settings.css
- includes/admin/feedzy-rss-feeds-actions.php
- includes/admin/feedzy-rss-feeds-import.php
- includes/views/import-metabox-edit.php
- includes/views/js/import-metabox-edit.js
- js/ActionPopup/index.js
Adds chain actions for custom field values.
Yes
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/688
> Adds actions support in custom fields

- includes/admin/feedzy-rss-feeds-import.php
- includes/views/import-metabox-edit.php
- includes/views/js/import-metabox-edit.js
Added support for multiple fallback images, allowing users to choose several images that will be applied randomly to imported items.
Yes
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/757
> Adds multiple fallback images support

- includes/admin/feedzy-rss-feeds-import.php
- includes/views/import-metabox-edit.php
- includes/views/js/import-metabox-edit.js
- tests/e2e/specs/upsell.spec.js
- tests/test-import.php
I have enhanced the duplicate removal process during import based on the suggestion provided here: https://github.com/Codeinwp/feedzy-rss-feeds/issues/1006#issuecomment-2540995371
Yes
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/1006
> Improved remove duplicates

- js/FeedzyLoop/components/FeedControl.js
- js/FeedzyLoop/placeholder.js
- tests/e2e/specs/loop.spec.js
Fixes the issue with Loop Block's load feed button not working with Feed Groups.
YES/NO
- Make sure the Loop works with both groups and URL.
* [x ] Code meets [WordPress Coding Standards](CONTRIBUTING.md#coding-standards) for PHP, HTML, CSS and JS
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/816.
> fix: Feedzy Loop button not working with Groups

- js/FeedzyBlock/Editor.js
- js/FeedzyBlock/index.js
- js/FeedzyBlock/inspector.js
- js/FeedzyBlock/radio-image-control/index.js
Using the global variable for dependencies works but the build files can not be properly scanned by WordPress i18n functions.
I switched to import from `package.json`, like the rest of the scripts.
NO
- Check if there is a regression with the build file.
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/978
> fix: use module import for deps in Block

- includes/admin/feedzy-rss-feeds-admin.php
Allow users to add group feed URLs using a per-line separator.
No
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/1008
> Fixed invalid feed URL issue when adding URLs per line

- includes/admin/feedzy-rss-feeds-admin.php
I've added a `Choose Language` select option to fix the issue with the initial translation action. 
Yes
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/769
> Fixed issue with initial translation action

- includes/abstract/feedzy-rss-feeds-admin-abstract.php
- includes/util/feedzy-rss-feeds-conditions.php
- phpstan-baseline.neon
Treated invalid thumbnails that don't respect the image format.
Reduce the number of phpstan errors.
YES
- Try to fetch an url without a valid image url like: https://wpshout.com/feed/
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/867
> fix: image handling in Feedzy RSS Feeds

- js/Conditions/ConditionsControl.js
NO
- Go to page and try to interact with filters.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/860
> fix: disable input elements in PRO upsell

- js/FeedzyBlock/Editor.js
- js/FeedzyBlock/attributes.js
- js/FeedzyBlock/inspector.js
- Solve various issues reported by the linter.
- Deprecated the Feedzy Classic Block HTTP selector for image. Only HTTPS will be used for image.
- Solve issue where user needs active groups to autocomplete.
YES
- Use Feeds which contain images: https://www.nasa.gov/feeds/iotd-feed/.
- Check if the images are displayed without regression.
- Create/Delete groups to check.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/865
> refactor: deprecate the Feedzy Classic Block http protocol selector

- includes/abstract/feedzy-rss-feeds-admin-abstract.php
- phpstan-baseline.neon
- tests/test-admin-abstract.php
- Fix image extraction for the function `feedzy_retrieve_image` by enforcing stricter type checking for return values
- Add unit tests for the function `feedzy_retrieve_image`
> [!NOTE]
> Added more `null` checks to prevent deprecation warnings.
NO
- Use feed `https://theprogressiveaspect.net/feed/` or `https://theprogressiveaspect.net/feed/`
- Check if there are no import errors reported with `DEBUG`
Closes #1114
> fix: image extraction on feeds item without image

- includes/admin/feedzy-rss-feeds-import.php
I have fixed the category setting that changed after installing the PRO version.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/915
> fix: category setting change on pro install

- js/ActionPopup/index.js
Close the action pop-up by clicking outside or pressing the Esc key.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/858
> Fixed close actions popup on outside click

- includes/admin/feedzy-rss-feeds-import.php
- Moved the YouTube handling from PRO to FREE (https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/922)
- Switched to `embed` instead of `video` shortcode since `embed` has support for YouTube shorts.
- Fixed various issues reported by PHPStan.
YES
- Use a link to a channel using YouTube Short (e.g. https://www.youtube.com/feeds/videos.xml?channel_id=UCSHmNs-_UuU1CfPhSbilTZQ ).
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/841
> feat: can now embed youtube videos and shorts

- css/settings.css
- includes/admin/feedzy-rss-feeds-import.php
- includes/views/import-metabox-edit.php
- includes/views/js/import-metabox-edit.js
Now the user can select between general settings and their custom fallback image.
YES
- Try to interact with the general feed settings in the import page.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/885#event-18809301811
> refactor: improved fallback settings for importer

- includes/abstract/feedzy-rss-feeds-admin-abstract.php
- includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php
- js/FeedzyBlock/Editor.js
- js/FeedzyBlock/attributes.js
- js/FeedzyBlock/inspector.js
- tests/e2e/specs/classic-block.spec.js
Added Aspect Ratio Options and Better Dimension Handling for thumbnail image control.
Inspired by WordPress Aspect Ratio's design.
YES
- Try to play with the Aspect Ratio selector.
- Also, check in an AMP environment
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/883
> feat: add aspect ratio control for Feedzy Classic Block

- css/settings.css
- includes/layouts/settings.php
Added helper information on proxy & user-agent.
YES
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/871
> feat: added helper notice for headers and proxy

- js/FeedzyBlock/Editor.js
- js/FeedzyBlock/inspector.js
Moved Feedzy classic sidebar settings to the top
YES
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/863
> refactor: moved classic sidebar settings

- includes/admin/feedzy-rss-feeds-admin.php
- includes/admin/feedzy-rss-feeds-import.php
- includes/feedzy-rss-feeds.php
- includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php
- includes/gutenberg/feedzy-rss-feeds-loop-block.php
- includes/views/css/import-metabox-edit.css
- includes/views/import-metabox-edit.php
- includes/views/js/import-metabox-edit.js
- js/FeedzyBlock/Editor.js
- js/FeedzyBlock/style.scss
- js/FeedzyLoop/placeholder.js
- tests/e2e/specs/classic-block.spec.js
- tests/e2e/specs/feed.spec.js
- tests/e2e/specs/loop.spec.js
Redesign the Edit Import Sources Configuration, Feedzy Classic and Loop Block. Now the user only needs 1 button to validate the input.
YES
https://github.com/user-attachments/assets/3f630807-c382-4ae4-abb6-4b9dfdfca979
https://github.com/user-attachments/assets/625093ad-0d1e-42c9-9fed-5a57cce6fcee
- Check the video/page.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/870
> feat: improved feeds validation UX

- css/settings.css
- feedzy-rss-feed.php
- includes/abstract/feedzy-rss-feeds-admin-abstract.php
- includes/admin/feedzy-rss-feeds-admin.php
- includes/admin/feedzy-rss-feeds-import.php
- includes/admin/feedzy-rss-feeds-log.php
- includes/admin/feedzy-rss-feeds-task-manager.php
- includes/feedzy-rss-feeds.php
- includes/layouts/feedzy-email-report.php
- includes/layouts/feedzy-logs-viewer.php
- includes/layouts/feedzy-tutorial.php
- includes/layouts/settings.php
- includes/views/js/import-metabox-edit.js
- js/feedzy-setting.js
- phpstan-baseline.neon
- tests/e2e/specs/logger.spec.js
- tests/e2e/utils.js
- tests/test-image-import.php
- tests/test-log.php
NO
- Run an import in Debug mode and check the Logs tab
- Check the errors when importing a bad feed
- Check the email with the reporting (you will have SMTP setup, and you can manually trigger the event [WP Control](https://wordpress.org/plugins/wp-crontrol/) plugin )
> [!IMPORTANT]
> Test with and without PRO version: https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/927
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/845
> [WIP] Add a logger

- css/settings.css
- includes/abstract/feedzy-rss-feeds-admin-abstract.php
- includes/admin/feedzy-rss-feeds-admin.php
- includes/feedzy-rss-feeds-activator.php
- includes/feedzy-rss-feeds-feed-tweaks.php
- js/categories.js
I have improved the feed group UX and added the default WP news group on activation.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/873
> Improved feed group UX

- includes/admin/feedzy-rss-feeds-admin.php
- includes/feedzy-rss-feeds.php
- includes/layouts/settings.php
- includes/views/import-metabox-edit.php
Removed description and changed the title.
YES
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/914
> refactor: UI for Schedule option in Settings

- includes/gutenberg/feedzy-rss-feeds-loop-block.php
- js/FeedzyLoop/block.json
- js/FeedzyLoop/controls.js
- js/FeedzyLoop/edit.js
- js/FeedzyLoop/editor.scss
- tests/e2e/specs/loop.spec.js
Added referral URL and layout change option, and moved cache time and sorting order option inside advanced panel.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/911
> Added referral url and change layout option

- includes/gutenberg/feedzy-rss-feeds-loop-block.php
- js/FeedzyBlock/inspector.js
- js/FeedzyLoop/block.json
- js/FeedzyLoop/components/FallbackImageLoader.jsx
- js/FeedzyLoop/controls.js
- js/FeedzyLoop/editor.scss
- js/FeedzyLoop/style.scss
- phpstan-baseline.neon
- tests/e2e/specs/loop.spec.js
Add Fallback Image per block for Feedzy Loop
YES
- Insert a Feedzy Loop
- Use a feed without an image or mixed (https://markteam.s3-tastewp.com/feed/)
- Check if the fallback image is displayed on both the editor and the frontend
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/832
> feat: add fallback image per import on Loop
