css/feedzy-rss-feeds.css
feedzy-rss-feed.php
includes/feedzy-rss-feeds.php
languages/feedzy-rss-feeds.pot
package.json
readme.txt

Fixed sdk notifications issues.
Added compatibility with pro version.

Release 3.1.5

---

css/feedzy-rss-feeds.css
feedzy-rss-feed.php
includes/feedzy-rss-feeds.php
package.json
tests/test-plugin.php

Added sdk test.

---

feedzy-rss-feed.php

Hi, just a small enhancement :-)

Replace default description placeholder text with actual info.

---

css/feedzy-rss-feeds.css
feedzy-rss-feed.php
form/form.php
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-ui-lang.php
includes/feedzy-rss-feeds-activator.php
includes/feedzy-rss-feeds.php
package.json
tests/bootstrap.php
tests/test-plugin.php

https://secure.helpscout.net/conversation/400212684/138350/?folderId=1088113
Solves URLs w. params

Fix: HelpScout - Issue: 138350

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

**NOTE:** It solves the Issue but it is a problem with his feed format not the way we interpret it, but I've added a correction for image URLs.

FIX: Solves issue 139393 on HS.

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/101

Cannot fetch image from custom XML element

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Some images do not render if they contain '+' or similar symbols

---

CHANGELOG.md
includes/feedzy-rss-feeds.php
readme.md
readme.txt
tests/bootstrap.php
themeisle-hash.json

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/153

build fails because of gutenberg resources

---

CHANGELOG.md
includes/abstract/feedzy-rss-feeds-admin-abstract.php
readme.md
readme.txt
themeisle-hash.json

do not ignore items with empty title

---

CHANGELOG.md
includes/abstract/feedzy-rss-feeds-admin-abstract.php
readme.md
readme.txt
tests/test-plugin.php
themeisle-hash.json

option to add nofollow attribute to shortcode

---

CHANGELOG.md
feedzy-rss-feed.php
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-admin.php
includes/feedzy-rss-feeds.php
includes/layouts/feedzy-support.php
includes/layouts/feedzy-tutorial.php
includes/layouts/feedzy-upsell.php
readme.md
readme.txt
tests/bootstrap.php
themeisle-hash.json

Improve UX on installation

---

includes/admin/feedzy-rss-feeds-ui.php
includes/feedzy-rss-feeds.php

Feedzy RSS icon opens up dashboard screen

---

CHANGELOG.md
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-ui-lang.php
includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php
includes/layouts/feedzy-support.php
readme.md
readme.txt
themeisle-hash.json

Fatal error: Too few arguments to function Feedzy_Rss_Feeds_Admin_Abstract::feedzy_retrieve_image

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

PHP Notice: Undefined index: follow in includes\abstract\feedzy-rss-feeds-admin-abstract.php on line 850

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-ui-lang.php

Adding error message when no items in feed

---

includes/layouts/feedzy-support.php
includes/layouts/feedzy-tutorial.php
includes/layouts/feedzy-upsell.php

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/158

getting started page on WP dashboard

---

form/form.php
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-ui-lang.php

outgoing links should have rel=noopener

---

CHANGELOG.md
css/feedzy-rss-feeds.css
feedzy-rss-feed.php
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/feedzy-rss-feeds.php
package.json
readme.md
readme.txt
themeisle-hash.json

Multifeed shows an error and no content if even one feed has an error

---

CHANGELOG.md
includes/abstract/feedzy-rss-feeds-admin-abstract.php
readme.md
readme.txt
themeisle-hash.json

Invalid argument supplied for foreach() in includes\abstract\feedzy-rss-feeds-admin-abstract.php on line 61

---

CHANGELOG.md
feedzy-rss-feed.php
form/form.php
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-ui.php
includes/admin/feedzy-wp-widget.php
includes/feedzy-rss-feeds-activator.php
includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php
includes/layouts/feedzy-support.php
includes/layouts/settings.php
phpcs.xml
readme.md
readme.txt
themeisle-hash.json

new PHPCS rules for strict comparison 

---

css/admin.css
css/feedzy-rss-feeds.css
feedzy-rss-feed.php
form/form.php
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-ui.php
includes/admin/feedzy-wp-widget.php
includes/feedzy-rss-feeds-activator.php
includes/feedzy-rss-feeds.php
includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php
includes/layouts/feedzy-support.php
includes/layouts/settings.php
phpcs.xml

CSS file being included on all pages

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Tags not closed when feed has no items

---

includes/admin/feedzy-rss-feeds-admin.php

Rename menu item in admin from Feedzy RSS to Feedzy

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Add filter to disable DB caching

---

readme.md
readme.txt

Tested upto 5.2

---

.travis.yml
CHANGELOG.md
readme.md
readme.txt
themeisle-hash.json

Travis builds for PHP below 5.6 fail with latest WP

---

includes/admin/feedzy-rss-feeds-admin.php

feedzy shortcode builder icon is not available in classic editor

---

includes/admin/feedzy-wp-widget.php

Widgets options not visible in customizer

---

readme.md
readme.txt

Readme: Specify that the templates are part of PRO

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

AMP URLs do not show the image

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-ui-lang.php

In the shortcode, separate behavior of meta into author, date and time

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

suppress warning and then reset at shutdown

---

includes/layouts/css/upsell.css
includes/layouts/feedzy-tutorial.php

onboarding screen looks bad on laptop

---

includes/admin/feedzy-rss-feeds-ui-lang.php

Add option to use default sorting when generating the shortcodep

---

css/feedzy-rss-feeds.css
feedzy-rss-feed.php
includes/admin/feedzy-rss-feeds-ui-lang.php
includes/feedzy-rss-feeds.php
package.json

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/213

Exclude by keywords work only for the title

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-ui-lang.php
readme.md
readme.txt

Allow ability to show date/time in WP timezone

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

 send formatted date/time to pro

---

.travis.yml
includes/abstract/feedzy-rss-feeds-admin-abstract.php

handle tz such as Asia/Kolkata

---

feedzy-rss-feed.php

Change upgrade link

---

.distignore
.gitignore
.travis.yml
bin/mysql/init-db.sql
bin/run-e2e-tests.sh
bin/wp-init.sh
cypress.env.json.template
cypress.json
cypress/docker-compose.yml
cypress/integration/shortcode_free.js
cypress/support/commands.js
cypress/support/index.js
docker-compose.travis.yml
package.json

Integrate Cypress.io

---

includes/admin/feedzy-wp-widget.php

Widget: Feed has no items cannot be overridden

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
tests/test-plugin.php

Ellipsis after summary cannot be replaced by using the filter feedzy_summary_output

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Summaries ending with E getting truncated

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-ui-lang.php

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/248

Extract categories from feed

---

includes/admin/feedzy-rss-feeds-ui-lang.php

Missing link label in the Feedzy shortcode in classic editor

---

.travis.yml
readme.md
readme.txt

Test with WP 5.3

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/feedzy-rss-feeds.php

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/258

Add logging to track usage (data based)

---

form/form.php
includes/abstract/feedzy-rss-feeds-admin-abstract.php

Item titles are shown as they are even if they contain HTML entities

---

includes/admin/feedzy-wp-widget.php

Widget does not use all settings configured

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Additional Class(es) in Gutenberg are not used

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

PHP Fatal error: Call to undefined method Feedzy_Rss_Feeds_Util_SimplePie::set_curl_options()

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Do not use force_feed for multiple URLs

---

readme.md
readme.txt

add in all missed change log history

---

includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php

never shows summary even if summary=yes in Gutenberg
https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/293

Problem with Youtube feed

---

includes/layouts/feedzy-support.php

Notice: Undefined index: tab

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Invalid feeds cause feedzy to hang

---

feedzy-rss-feed.php
includes/layouts/feedzy-improve.php
includes/layouts/feedzy-support.php

Add the "help us improve!" tab for surveys

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Conflict with Rss Aggregator in gutenberg editor

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-ui.php

Using multiple feeds in shortcode throws warning

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Notice: Undefined index: host when item has no link element

---

CHANGELOG.md
includes/admin/feedzy-wp-widget.php
readme.md
readme.txt
themeisle-hash.json

PHP Notice: Undefined index errors in the widget

---

CHANGELOG.md
includes/admin/feedzy-rss-feeds-admin.php
includes/feedzy-rss-feeds-activator.php
includes/feedzy-rss-feeds-deactivator.php
includes/feedzy-rss-feeds.php
readme.md
readme.txt
themeisle-hash.json

bulk activation of plugin aborts activation of subsequent plugins

---

cypress/integration/gutenberg_free.js
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php

Cache duration does not work; cache is always set to 12 hours

---

cypress/integration/import_feed_free.js
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-import.php
includes/admin/feedzy-rss-feeds-ui.php

https://github.com/codeinwp/feedzy-rss-feeds-pro/issues/188

Use SimplePieItem's get_id to determine uniqueness of items

---

includes/admin/feedzy-rss-feeds-import.php

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/337

Change cache time to 55 minutes so that feed2post can see new items in the next run

---

includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php
includes/views/css/import-metabox-edit.css
includes/views/import-metabox-edit.php

Changes related to https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/327

Add support for non English text while extracting full content

---

includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-ui-lang.php
includes/layouts/feedzy-tutorial.php
includes/layouts/feedzy-upsell.php

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/339

Rewording upgrade texts to indicate correct higher version

---

includes/admin/feedzy-rss-feeds-import.php
includes/feedzy-rss-feeds.php
includes/views/js/import-metabox-edit.js

Conflict with Ultimate CSV Importer

---

includes/admin/feedzy-rss-feeds-import.php

https://github.com/Codeinwp/feedzy-rss-feeds/issues/436

notify full content validation errors

---

includes/admin/feedzy-rss-feeds-import.php
includes/feedzy-rss-feeds.php
includes/views/js/import-metabox-edit.js

Feed2Post: Ability to clear data of already imported items to reimport those again

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php
readme.md
readme.txt

Test against WP 5.5

---

includes/admin/feedzy-rss-feeds-import.php

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/355

[F2P] Post author checkboxes can't be unchecked once enabled

---

includes/admin/feedzy-rss-feeds-import.php
includes/feedzy-rss-feeds.php

Link imports to posts and pages

---

cypress.json
includes/admin/feedzy-rss-feeds-import.php
tests/test-import.php
tests/test-plugin.php

cypress: HTML tags are trimmed on save of the import job

---

includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php
tests/test-import.php
tests/test-plugin.php

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/357

Issue 357 pro

---

cypress/integration/import_feed_free.js
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-import.php
includes/views/css/import-metabox-edit.css
includes/views/import-metabox-edit.php
includes/views/js/import-metabox-edit.js

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/348

improve UX for add/edit import screen

---

includes/views/css/import-metabox-edit.css
includes/views/import-metabox-edit.php

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/348#issuecomment-702762234

make upsell text more visible

---

css/feedzy-rss-feed-import.css
css/feedzy-rss-feeds.css
cypress/integration/import_feed_free.js
feedzy-rss-feed.php
includes/admin/feedzy-rss-feeds-import.php
includes/feedzy-rss-feeds.php
includes/views/js/import-metabox-edit.js
package.json

Improve UI of the import listing page

---

includes/admin/feedzy-rss-feeds-import.php

Random image generator link doesn't work on feeds without images

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Enclosures that do no specify image extension are not imported even if type is image/jpeg

---

includes/admin/feedzy-rss-feeds-import.php

https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/363

Add support for custom tags for attaching featured image

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-import.php
includes/feedzy-rss-feeds.php

https://github.com/codeinwp/feedzy-rss-feeds-pro/issues/362

[F2P] When keywords filter is used for import job - Custom tags are being taken from incorrect items

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-import.php
includes/views/import-metabox-edit.php

https://github.com/codeinwp/feedzy-rss-feeds-pro/issues/213

Make exclude/include by keywords work for content as well

---

bin/run-e2e-tests.sh
bin/wp-init.sh
cypress.json
cypress/integration/import_feed_free.js
cypress/integration/import_feed_free_image.js
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-import.php
includes/feedzy-rss-feeds.php
includes/views/css/import-metabox-edit.css
includes/views/import-metabox-edit.php
includes/views/js/import-metabox-edit.js

Feed2Post - Default Featured Image

---

includes/views/import-metabox-edit.php

Fix display custom fields issue in import wizard 

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Exclude DC namespace validation when feed URL doesn't have

---

includes/admin/feedzy-rss-feeds-import.php

Save custom field name and value

---

includes/views/misc-view.php

Close Codeinwp/feedzy-rss-feeds-pro#389

Fix escaping and PHP errors

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Thumbnails dimension block setting not working on front-end

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Close #541 
Fix Codeinwp/feedzy-rss-feeds-pro#371
Fix #527

Improve DC namespace validation

---

includes/admin/feedzy-rss-feeds-admin.php

Close Codeinwp/feedzy-rss-feeds-pro#397

Change 2nd time validation message when author empty

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Close Codeinwp/feedzy-rss-feeds-pro#131

Add default value of fields if fields data empty

---

includes/admin/feedzy-rss-feeds-import.php
includes/views/css/import-metabox-edit.css

Fix broken style issue in feedzy list page

---

includes/admin/feedzy-rss-feeds-import.php

Fix feed import attachment issue

---

css/feedzy-rss-feeds.css

Close Codeinwp/feedzy-rss-feeds-pro#404

Fix shows less columns issue in gutenberg block

---

cypress/integration/gutenberg/gutenberg_free.js
includes/views/css/import-metabox-edit.css

Fix broken icon issue in chosen dropdown

---

includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php

Fix PHP notices on widget block area

---

includes/admin/feedzy-rss-feeds-import.php

Fix undefined function error when run cron job

---

includes/admin/feedzy-rss-feeds-import.php

Add new line character support with import content

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Fix broken feed image issue in 3.7.4

---

includes/admin/feedzy-rss-feeds-import.php

Close Codeinwp/feedzy-rss-feeds-pro#398

Fix import custom value when using #item_full_content shortcode

---

includes/admin/feedzy-rss-feeds-import.php

Show the import job title in post row action

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Add default thumbnail image support in external image

---

css/metabox-settings.css

Fix style issue in setting fields

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Close Codeinwp/feedzy-rss-feeds-pro#436

Fix keyword filtering issue when select description field

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-import.php

Close Codeinwp/feedzy-rss-feeds-pro#432

Fetch image from themeisle service API

---

includes/admin/feedzy-rss-feeds-admin.php
includes/feedzy-rss-feeds.php

Remove elementor hidden WP widget feature

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Close Codeinwp/feedzy-rss-feeds-pro#445

Fix keyword filter issue with date filter

---

cypress/integration/default/import_feed_free.js
cypress/integration/gutenberg/gutenberg_free.js
includes/admin/feedzy-rss-feeds-admin.php

Issue - Codeinwp/feedzy-full-post#23

Fix cURL timeout error

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Fix PHP Notice/Warning

---

css/feedzy-rss-feeds.css
includes/abstract/feedzy-rss-feeds-admin-abstract.php

Fix broken style

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php

Resolved Deprecated functions error messages with PHP 8.1  #654 
I have found following deprecated  warnings with PHP version 8.1 and resolved it based on that. Could you please check?
https://www.awesomescreenshot.com/image/27548839?key=b5a1d6cd40672bac95e91b21bf3aaf2e

Fix Deprecated functions error messages with PHP 8.1

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Display image from description element

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Exclude emoji images from feed import

---

css/feedzy-rss-feeds.css

Add lazy load images support

---

js/feedzy-setting.js

Close Codeinwp/feedzy-rss-feeds-pro#468

Fix wordai and spinnerchief integration issue

---

includes/views/import-metabox-edit.php

Typo in import setting page

---

includes/layouts/feedzy-tutorial.php

Remove duplicate upsell card in support page

---

css/feedzy-rss-feed-import.css
css/form.css
includes/feedzy-rss-feeds-feed-tweaks.php

Fix tinymce broken UI

---

css/feedzy-rss-feed-import.css
includes/admin/feedzy-rss-feeds-import.php
includes/views/js/import-metabox-edit.js

Change success message text color

---

includes/layouts/feedzy-improve.php

Remove duplicate text in help us Improve tab

---

includes/feedzy-rss-feeds-feed-tweaks.php

Fix external image size issue

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Fix auto delete cache issue

---

includes/admin/feedzy-rss-feeds-admin.php

Fix PHP fetal error

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Fix cache duration time issue

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Reg: Fix cache duration time issue

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/views/js/import-metabox-edit.js

Close Codeinwp/feedzy-rss-feeds-pro#494

Improve keyword excluding

---

includes/elementor/widgets/register-widget.php

Close Codeinwp/feedzy-rss-feeds-pro#493

Remove unnecessary filter option

---

includes/admin/feedzy-rss-feeds-import.php

Close Codeinwp/feedzy-rss-feeds-pro#508

Improve content rephrasing service API calls

---

includes/views/import-metabox-edit.php

Close Codeinwp/feedzy-rss-feeds-pro#497

Fix English to Swedish translation issue

---

includes/views/js/import-metabox-edit.js

Improve tagify js element focus

---

css/settings.css

Fixed tagify tags style issue

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-import.php

Close Codeinwp/feedzy-rss-feeds-pro#504

Fixed cron job image import issue

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Close Codeinwp/feedzy-rss-feeds-pro#518

Fixed security vulnerability issue

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Improve shortcode className parameter

---

includes/admin/feedzy-rss-feeds-ui-lang.php
includes/elementor/widgets/register-widget.php
includes/feedzy-rss-feeds-feed-tweaks.php

Added new filter for classic/elementor widget

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Close Codeinwp/feedzy-rss-feeds-pro#516 Codeinwp/feedzy-rss-feeds-pro#517

Fixed PHP notice and lazy load issue

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Close Codeinwp/feedzy-rss-feeds-pro#511

Fixed render default img issue

---

includes/util/feedzy-rss-feeds-util-simplepie.php

Fixed transient cache mechanization

---

tests/test-import.php
tests/test-plugin.php

PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/722

Fixed phpunit testcase error

---

includes/views/spinnerchief-view.php

Close Codeinwp/feedzy-rss-feeds-pro#533

Compatible with new spinnerchief API

---

includes/admin/feedzy-rss-feeds-import.php
tests/test-import.php

Close Codeinwp/feedzy-rss-feeds-pro#542

Feed import exclude default category

---

includes/layouts/feedzy-tutorial.php

Changed the document URL for the support page

---

includes/admin/feedzy-rss-feeds-import.php
includes/views/js/import-metabox-edit.js

Close Codeinwp/feedzy-rss-feeds-pro#534

Removed imported posts when the job is purged and reset

---

includes/admin/feedzy-rss-feeds-import.php

Close Codeinwp/feedzy-rss-feeds-pro#559

Fixed multiple attachments generating issue

---

includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php
includes/feedzy-rss-feeds.php
includes/layouts/settings.php
js/feedzy-setting.js

Close Codeinwp/feedzy-rss-feeds-pro#550

Added custom cron scheduler support

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Fixed duplicate/delete item issue

---

cypress/support/index.js
includes/admin/feedzy-rss-feeds-import.php

Fixed duplicate items import issue

---

includes/admin/feedzy-rss-feeds-import.php

Fixed conflict with ACF plugin

---

includes/admin/feedzy-rss-feeds-import.php

Added cron job retry method

---

includes/admin/feedzy-rss-feeds-import.php

Fixed set custom featured image issue

---

includes/admin/feedzy-rss-feeds-admin.php

Fixed onboarding wizard js console error

---

composer.lock
css/feedzy-rss-feed-import.css
feedzy-rss-feed.php
includes/admin/feedzy-rss-feeds-admin.php

Close Codeinwp/feedzy-rss-feeds-pro#578

Added about page integration

---

includes/feedzy-rss-feeds.php

Close Codeinwp/feedzy-rss-feeds-pro#583

Removed powered by branding label

---

includes/admin/feedzy-rss-feeds-import.php
includes/views/js/import-metabox-edit.js

Close Codeinwp/feedzy-rss-feeds-pro#582

Fixed import job page loading issue

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
js/feedzy-lazy.js

Improved lazy load endpoint performance

---

css/settings.css
includes/admin/feedzy-rss-feeds-admin.php
includes/feedzy-rss-feeds.php
includes/layouts/settings.php
js/feedzy-setting.js

Fixed minor layout issue

---

includes/feedzy-rss-feeds-feed-tweaks.php

Close Codeinwp/feedzy-rss-feeds-pro#593

Fixed external image support issue with Elementor

---

cypress/e2e/gutenberg/gutenberg_free.js

Fixed: e2e gutenberg testcase error

---

includes/admin/feedzy-rss-feeds-import.php
includes/views/import-metabox-edit.php
includes/views/js/import-metabox-edit.js

Close Codeinwp/feedzy-rss-feeds-pro#569

Added support to create a dynamic category

---

includes/admin/feedzy-rss-feeds-admin.php

Fixed categories feed URL sanitization issue

---

readme.txt

Issue Codeinwp/feedzy-rss-feeds-pro/issues/589

Changed WP required version

---

includes/feedzy-rss-feeds-feed-tweaks.php

Close Codeinwp/feedzy-rss-feeds-pro#622

Fixed security issue with rest api

---

cypress/e2e/default/import_feed_free.js
includes/layouts/feedzy-support.php

Fixed typo in support page

---

includes/layouts/settings.php

Close : Codeinwp/feedzy-rss-feeds-pro#632

Change wording for first execution time field.

---

includes/admin/feedzy-rss-feeds-admin.php

Close Codeinwp/feedzy-rss-feeds-pro#649

Sanitize missing setting fields

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Close Codeinwp/feedzy-rss-feeds-pro#650

Fixed authenticated blind SSRF attack

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Close Codeinwp/feedzy-rss-feeds-pro#651

Fixed error messages escaping issue

---

includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php
includes/layouts/settings.php
includes/views/misc-view.php

Separate settings in General section to prevent confusion

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Close Codeinwp/feedzy-rss-feeds-pro#655

Improved remote get method to stop blind SSRF attack

---

includes/admin/feedzy-rss-feeds-admin.php

Fixed invalid feed issue with white space

---

includes/admin/feedzy-rss-feeds-import.php

PR  Codeinwp/feedzy-rss-feeds-pro#663

Fixed PHP variable undefined error

---

includes/admin/feedzy-rss-feeds-actions.php

Close Codeinwp/feedzy-rss-feeds-pro#668

Fixed default image tag support issue

---

includes/layouts/feedzy-pro.php

Close Codeinwp/feedzy-rss-feeds-pro#673

Updated support dashboard page

---

includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php

Fix actions allowing non-admin users to take action if a valid nonce was passed
Check the linked issue for testing details.
Closes: Codeinwp/feedzy-rss-feeds-pro#680

fix: authorization for page creation

---

includes/admin/feedzy-rss-feeds-import.php

Prepare and better sanitize the search query for custom fields
Follow the replication steps from the linked issue.
Check the response returned.
Closes: Codeinwp/feedzy-rss-feeds-pro#679

fix: reported query vulnerability

---

includes/admin/feedzy-rss-feeds-import.php

Move the checking for existing featured images before trying to run the job for image generation (like ChatGPT)
For detect this, you will need to use the log file.
- Have the ChatGPT integration active for a feed.
- In your testing instance, activate the debug logs. ( Also have a plugin that lets you see the logs).
- With a plugin like WPIDE, you have to edit this file: https://github.com/Codeinwp/feedzy-rss-feeds/blob/6d428233e5f88f7889c361618936235b9b7a93d5/includes/admin/feedzy-rss-feeds-actions.php#L461
- After line 460, add this code `error_log('Image generation with ChatGPT triggered');`
- Now try to add a feed and import some posts.
- You will generate the initial images saved in the Media Library. Also, the message from above will be found in the logs.
- Press `Purge & Reset` for …

fix: try reuse image before generating

---

includes/admin/feedzy-rss-feeds-import.php

In this PR, I've allowed all WordPress post content HTML tags to fix the issue with WordPress.com.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/683

Allowed all default WP post content html tags

---

.github/workflows/test-php.yml
feedzy-rss-feed.php
form/form.php
includes/abstract/feedzy-rss-feeds-admin-abstract.php
includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php
includes/admin/feedzy-rss-feeds-ui-lang.php
includes/admin/feedzy-rss-feeds-ui.php
includes/elementor/controls/template-layout.php
includes/elementor/feedzy-rss-feeds-elementor.php
includes/elementor/widgets/register-widget.php
includes/feedzy-rss-feeds-feed-tweaks.php
includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php
includes/layouts/feedzy-pro.php
includes/layouts/feedzy-support.php
includes/layouts/setup-wizard.php
includes/views/amazon-product-advertising-view.php
includes/views/import-metabox-edit.php
includes/views/misc-view.php
includes/views/openai-view.php
includes/views/spinnerchief-view.php
includes/views/wordai-view.php
js/FeedBack/feedback-form.js
js/FeedzyBlock/Editor.js
js/FeedzyBlock/inspector.js
phpcs.xml
tests/e2e/specs/upsell.spec.js

Changes:
- add missing translator comments
- add localization for upgrade URLs
Generated `.pot` file: [feedzy-free.pot.zip](https://github.com/user-attachments/files/17308979/feedzy-free.pot.zip) (with command `wp i18n make-pot . languages/feedzy-free.pot`)
NO
- Check if the strings and upgrade URL are in the correct format.
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/978

fix: translation string

---

includes/layouts/feedzy-documentation.php
includes/layouts/feedzy-improve.php
includes/layouts/feedzy-pro.php
includes/layouts/feedzy-tutorial.php
js/ActionPopup/SortableItem.js
js/FeedzyBlock/Editor.js
js/FeedzyBlock/inspector.js

Added missing strings.
New pot file: [feedzy-rss-feeds.pot.zip](https://github.com/user-attachments/files/17522678/feedzy-rss-feeds.pot.zip)
NO
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/978

fix: missing translations

---

.github/workflows/test-php.yml
includes/admin/feedzy-rss-feeds-actions.php

In this PR I've Replaced prompt content from the rewrite content for some specific cases.
More details here: https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/724#issuecomment-2152632499
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro#724

[Paraphrase with ChatGPT] Removed prompt content text

---

includes/admin/feedzy-rss-feeds-actions.php

I've trim the double quotes.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/770

Removed double quotes from paraphrased text

---

.distignore
includes/admin/feedzy-rss-feeds-admin.php
includes/feedzy-rss-feeds-feed-tweaks.php
includes/feedzy-rss-feeds.php
js/Review/index.js
package.json

It adds a review request to Imports page when all of the following conditions are true:
- The plugin has been installed for at least a week. It is saved in `feedzy_rss_feeds_install` option.
- At least one import job has imported at least 100 posts.
YES
- Once all the described conditions are true, confirm the modal appears in the Imports page.
- If any of that is not true, it shouldn't appear.
- Make sure it goes away once you dismiss.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/771.

 feat: add review modal

---

css/feedzy-rss-feed-import.css
css/settings.css
feedzy-rss-feed.php
includes/admin/feedzy-rss-feeds-actions.php
includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php
includes/feedzy-rss-feeds-limited-offers.php
includes/feedzy-rss-feeds.php
includes/layouts/header.php
includes/layouts/integration.php
includes/views/amazon-product-advertising-view.php
includes/views/import-metabox-edit.php
includes/views/openai-view.php
includes/views/openrouter-view.php
includes/views/spinnerchief-view.php
includes/views/wordai-view.php
js/ActionPopup/SortableItem.js
js/ActionPopup/index.js
js/feedzy-setting.js

More details here - https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/795#issue-2735579565
Yes
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/792

Improvement in AI API integration

---

includes/admin/feedzy-rss-feeds-import.php

If the user has defined any category to the import, we don't need to append the default category on top of it.
YES/NO
- After an import is run, make sure the default category is only set if no other categories exist.
- If the user has selected a category, the default shouldn't be attached to the post.
- Make sure there are no debugging logs.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/654.

fix: handle default category gracefully

---

includes/admin/feedzy-rss-feeds-actions.php
js/ActionPopup/SortableItem.js

This PR adds support for Regular expression support to Search/Replace feature.
No
- Make sure the Search replace works like it was doing previously when used with simple strings.
- When used with a Regular expression, it should properly detect and replace the strings. You can use ChatGPT to generate and https://regex101.com/ to test Regex.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/627.

feat: add regex support to Search/Replace action

---

includes/admin/feedzy-rss-feeds-import.php
includes/feedzy-rss-feeds-feed-tweaks.php
includes/feedzy-rss-feeds.php
includes/views/css/import-metabox-edit.css
includes/views/js/import-metabox-edit.js
tests/e2e/specs/upsell.spec.js
tests/e2e/utils.js

Adds import/export job configuration.
Yes
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/775

Adds import/export configuration

---

css/settings.css
includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php
includes/layouts/settings.php
includes/views/import-metabox-edit.php
tests/e2e/specs/upsell.spec.js

Automatically deletes the featured image when the auto-delete posts feature is enabled.
Yes
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/827

Adds auto-delete featured image

---

includes/admin/feedzy-rss-feeds-import.php

I've fixed the global fallback image issue with free users.
Yes
Closes https://github.com/Codeinwp/feedzy-rss-feeds/issues/1052

Fixed global fallback image issue

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php

Update the user agent for simplepie.
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/826

Update user-agent for simplepie

---

includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php
includes/layouts/setup-wizard.php
js/feedzy-setup-wizard.js

- Add a skip button for Step 2.
- Add option to set the status of the imported feed.
- Created import feed settings will now be set to draft to allow the user to run it manually.
- On Feed choice, redirect to the created import feed settings page instead of the import feeds settings list.
Yes
https://github.com/user-attachments/assets/a213ca9e-6df9-4ebb-a385-ee7ffc7a7058
https://github.com/user-attachments/assets/4cf7af37-b8a1-48ea-b9a5-87cbbeb3b05f
- Check the steps like in the above videos
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/905

feat: onboarding steps

---

includes/abstract/feedzy-rss-feeds-admin-abstract.php
tests/test-admin-abstract.php

The `feedzy_image_encode` was malforming the `$img_url` in case of links like `https://heavy.com/wp-content/uploads/2025/05/GettyImages-2172500144.jpg?quality=65&strip=all` where `$url_tab['query']` was available to process. This was caused because `$img_url` was used as an out variable for `&$matches` param.
https://github.com/Codeinwp/feedzy-rss-feeds/blame/ad9a9b302ec1e91b3183bde8a56e4300062e4608/includes/abstract/feedzy-rss-feeds-admin-abstract.php#L1870
```php
preg_match_all( '/(http|https):\/\/[^ ]+(\.gif|\.GIF|\.jpg|\.JPG|\.jpeg|\.JPEG|\.png|\.PNG)/', $url_tab['query'], $img_url );
if ( isset( $img_url[0][0] ) ) {
$img_url = $img_url[0][0];
}
```
To fix, I used a separated variable for `preg_match_all` which does not modify the `$img_url`
NO
- Make a Feedzy group with those links …

fix: usage of `preg_match_all` out variable

---

css/feedzy-rss-feed-import.css
includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php
includes/feedzy-rss-feeds-limited-offers.php
includes/views/js/import-metabox-edit.js

- Remove all notices on page with the exception of `fz-notice` and `themeisle-sale` (Black Friday)
- Previously, the CSS page was loaded on all the pages! Now it is restricted to our plugin pages.
YES
- Use https://github.com/Soare-Robert-Daniel/test-black-friday for testing the Black Friday banner.
- Use this tool plugin to have notice displayed [notice-tester.zip](https://github.com/user-attachments/files/21369507/notice-tester.zip)
- Check if non-feedzy notices are hidden
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/869

fix: remove all other notices on plugin pages

---

readme.txt

updated faq

---

includes/admin/feedzy-rss-feeds-admin.php
includes/admin/feedzy-rss-feeds-import.php
includes/views/css/import-metabox-edit.css
includes/views/js/import-metabox-edit.js
tests/e2e/specs/feed.spec.js
tests/e2e/specs/import.spec.js
tests/e2e/utils.js

Update the UI for upsell modal on new import, export/import settings and clone
YES
https://github.com/user-attachments/assets/ab5f662e-d4db-44b1-b080-239dae548d06
- Check if the new design is functional (link redirect, modal closing)
Closes https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/868

refactor: UI upsell modal for export/import, clone, import

---

includes/layouts/settings.php
includes/views/import-metabox-edit.php

Removed description and link documentation.
NO

fix: visual issues
